version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: brainuser
      POSTGRES_PASSWORD: Brainq1w2e3@
      POSTGRES_DB: brain-agriculture
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
